version: "3"
networks: 
    localdev:
        name: localdev
services:
    web:
        build: eShopWeb.WebApi
        ports:
            - "7000:80"
        depends_on:
            - db-server
        networks: 
            - localdev    
    db-server:
        image: eshopwebwebapi:dev
        container_name: db-server
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
            MSSQL_TCL_PORT: 1433
        ports: 
            - "1433:1433"
        networks: 
            -localdev    